FROM hseeberger/scala-sbt:17.0.1_1.5.5_2.13.6 AS build

ARG SERVICE_NAME

# Installiere notwendige Pakete für JavaFX und X11-Forwarding
USER root
RUN apt-get update && apt-get install -y \
    libx11-6 \
    libxxf86vm1 \
    libxext6 \
    libxrender1 \
    libxtst6 \
    libxi6 \
    libgl1-mesa-glx \
    libgtk-3-0 \
    x11-apps


WORKDIR /app
COPY ./ /app

RUN sbt clean gameUi/assembly

FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      openjdk-21-jre-headless \
      libx11-6 libxxf86vm1 libxext6 libxrender1 libxtst6 libxi6 \
      libgl1-mesa-glx libegl1 libgles2-mesa libgtk-3-0 x11-apps && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/game-ui/target/scala-3.5.0/ui-assembly-0.1.0-SNAPSHOT.jar /app/ui.jar

EXPOSE 9000
CMD [ "java", "-jar", "/app/ui.jar", "0.0.0.0", "ui" ]